### ISSUE TITLE
Flags represent countries, not languages

### ISSUE THREAD

**Issue by skripnik** [backmeupplz/magicpill#6]
It's easy to make language switcher using countries emoji, but it's just incorrect. Especially on the website that tries to look scientific.

**Comment by backmeupplz** [comment]
🤔 what do you suggest to use instead?

**Comment by skripnik** [comment]
A standard HTML dropdown:

Language: English ▼

**Comment by backmeupplz** [comment]
🤔 sounds more like a nitpick to me tbh
